### ISSUE TITLE
Make error messages transparent

### ISSUE THREAD

**Issue by lucca65** [BeSpiral/eosrpc-elixir-wrapper#2]
Right now all our blockchain errors are hidden by "Internal Errors" we need to make those behave correctly:

throws exceptions when there are `!` (bangs) on the related methods and return error tuple (`{:error, reason}` when not

**Comment by ajose01** [comment]
I can take a crack at it. any contribution guidelines?

**Comment by lucca65** [comment]
We don't have any just yet, added a issue for that #4. By now just the usual stuff, documentation if possible inside elixir, and PR closing the issue (:

**Comment by lucca65** [comment]
Fixed on [0.4.0](https://github.com/BeSpiral/eosrpc-elixir-wrapper/releases/tag/0.4.0) release
